### ISSUE TITLE
Warning for unconfirmed TVL being reached

### ISSUE THREAD

**Issue by vitsalis** [babylonchain/simple-staking#134]
The staking form should be enabled in the following condition: `confirmedTVL < stakingCap || confirmedTVL + unconfirmedTVL < stakingCap`. Let's explore why the different cases might happen and whether we should display a warning:

- `confirmedTVL < stakingCap`: This condition happens when the total confirmed value is less than the staking cap, meaning that users still have a chance of getting in.
     - If `confirmedTVL < stakingCap && confirmedTVL + unconfirmedTVL < stakingCap`, then no warnings should be displayed.
     - If `confirmedTVL < stakingCap && confirmedTVL + unconfirmedTVL >= stakingCap`, the user can still stake, but we should display a warning: "The signet Bitcoin ledger contains unconfirmed transactions that once confirmed will fill the staking cap. Think twice before staking as your transaction might not be activated. If your transaction is not activated, you can still on-demand unbond it."
- `confirmedTVL + unconfirmedTVL < stakingCap`: This condition happens either when the staking cap is not filled or when the staking cap is filled, but there are unconfirmed unbonding transactions.
     - If `confirmedTVL + unconfirmedTVL < stakingCap && confirmedTVL < stakingCap` (same condition as the first bullet above): All good, show without any warnings.
     - If `confirmedTVL + unconfirmedTVL < stakingCap && confirmedTVL >= stakingCap`, the staking cap has been reached, but there are unconfirmed unbonding transactions that will fill more space. The staking form should display the warning: "The signet Bitcoin ledger contains unconfirmed unbonding transactions that once confirmed will open space for more staking transactions to be activated. However, the confirmation of the unbonding transactions is not guaranteed. Think twice before staking as your transaction might not be activated. If your transaction is not activated, you can still on-demand unbond it."

**Comment by vitsalis** [comment]
Update after discussion with @fishermanymc . The above is too complicated, let's have the following:

- Staking is enabled if and only if `confirmed < cap`.
- Whenever `confirmed + unconfirmed > cap * 0.8` (0.8 should be a constant) and staking is allowed, we display the warning "the staking cap might have already been filled when your staking tx enters Signet BTC ledger. In that case your stake will be labelled as overflow, and you will be required to unbond and withdraw it."

**Comment by fishermanymc** [comment]
OK, more proper and succinct language:
"Your stake may overflow the staking TVL cap and need to be unbonded and
withdrawn, which will cost you extra transaction fees. So please think
twice before staking."
Indeed, I think we should always show this, instead of only showing it
above 80%. It is likely that our TVL goes from 0 to the cap in one to two
blocks, then people may blame us for not telling them.

**Comment by jrwbabylonchain** [comment]
https://github.com/babylonchain/simple-staking/pull/147

**Comment by jrwbabylonchain** [comment]
<img width="361" alt="image" src="https://github.com/babylonchain/simple-staking/assets/154598612/df01efe1-16f0-454b-a25a-1c19ef176a9c">
reopen this issue as requirement changed again to highlight the warning at the staking form level
