### ISSUE TITLE
Ability to change between Signet and Mainnet using env variable

### ISSUE THREAD

**Issue by gbarkhatov** [babylonchain/simple-staking#14]
- Headers, paragraphs, tooltips. All the text should be changed
- Wallet
- Mempool endpoints
- Other stuff

We shall offer a button where user can click and switch between different envs. and this button shall also make sure it trigger the switchNetwork API from the wallet.

**Comment by jrwbabylonchain** [comment]
hi @gbarkhatov would u mind put the issue under the `web services` project when creating? otherwise it won't be visible from the board

**Comment by jrwbabylonchain** [comment]
Updated the description to make sure it involve the wallet API to switch between envs

**Comment by gbarkhatov** [comment]
Closed in #193
