### ISSUE TITLE
Retrieve pending TVL from the API

### ISSUE THREAD

**Issue by vitsalis** [babylonchain/simple-staking#54]
This is pending API implementation cc @jrwbabylonchain

**Comment by jrwbabylonchain** [comment]
@gbarkhatov we renamed the field from `unconfirmed_active_tvl` to `unconfirmed_tvl`. captured here: https://github.com/babylonchain/simple-staking/pull/63

**Comment by gbarkhatov** [comment]
@jrwbabylonchain just to confirm that this ticket should be closed, right?
