### ISSUE TITLE
Point to the finality provider registration docs

### ISSUE THREAD

**Issue by gbarkhatov** [babylonchain/simple-staking#61]
This should be pointing to the finality provider registration docs for phase-1, let's add a TODO and issue for this.

_Originally posted by @vitsalis in https://github.com/babylonchain/simple-staking/pull/60#discussion_r1595425605_

**Comment by vitsalis** [comment]
This can be the link: https://github.com/babylonchain/networks/tree/main/bbn-test-4/finality-providers
