### ISSUE TITLE
Allow signet to use testnet at `toNetwork` method

### ISSUE THREAD

**Issue by jrwbabylonchain** [babylonchain/simple-staking#65]
The `Network` type supports `signet` but the actual method of managing the networks does not
i.e https://github.com/babylonchain/simple-staking/blob/main/src/utils/wallet/index.ts#L13

**Comment by gbarkhatov** [comment]
Can you please provide the description here @jrwbabylonchain ?

**Comment by jrwbabylonchain** [comment]
@gbarkhatov updated and simple PR here: https://github.com/babylonchain/simple-staking/pull/69
