### ISSUE TITLE
Activation Height faults

### ISSUE THREAD

**Issue by vitsalis** [babylonchain/simple-staking#68]
Some issues with the current versions activation height methodology on the front-end:

The app uses the current BTC height for choosing parameters, instead of the next one.
1. Doesn’t make sense as the staking will most probably be included in the next block.
2. The app does not display the staking form if the BTC height of the first staking activation height is not reached.
3. Happens when we are close before a parameters update: The app might send a staking transaction that will be included in a block where the next set of parameters take into effect.
    - This might mean that someone might stake with the wrong parameters and their stake not recognised.
4. Happens when we are close after a parameters update: The app might send a staking transaction, that in the case of a re-org might be included in a block before the parameters that were used for it take into effect.

We can solve all of the above using the following mechanism:

- The height which defines the parameters we should choose is `h = CurrentBTCHeight`. We use this in order for the tx to be accepted due to the 4th bullet point.
- (Solves 2): If `h < Version0.ActivationHeight`, show a “Coming Soon” text. This is basically the text we display before the staking system opens.
- (Solves 3): If `h >= Version0.ActivationHeight and h + ConfirmationDelta >= NextVersion.ActivationHeight`  disable the staking form with the text `The staking parameters of the system are being updated, new submissions will be allowed in x BTC blocks` (where `x` is how far away the current height is from the next activation height).
    - `ConfirmationDelta` is the parameter specifying how many BTC blocks away we want to be before we disable the staking form. It can be the same confirmation delta defined in the global params.
    - `NextVersion` is the version that applies immediately after the version height `h` is included in.
    - Indirectly solves (1) if `ConfirmationDelta > 1`, as we will be disabling close to the height in which the transactions will be updated.
- (Solves 4): Otherwise, display the staking form as usual, but set the `LockTime` field of the staking transaction to `CurrentVersion.ActivationHeight`
     - This is a field that tells Bitcoin that this transaction should be included at a block with a height that is `>= LockTime`. Kudos to @KonradStaniec for this neat solution.
     - An issue with this is that the staking transaction will be rejected by mempool if we send it with a LockTime < currentHeight. As we set this to the current height which we received from mempool, we should not encounter issues. If we encounter issues with the submission, we tell the user to try again.

**Comment by vitsalis** [comment]
A revision of the above:

- The staking app expects that its staking transactions will be included in `currentBTCHeight + 1`. Thus, it should use this height when choosing parameters, i.e. `params = getParams(versions, currentBTCHeight + 1)`
    - Furthermore, the staking dApp should be activated when `currentBTCHeight + 1 == version0.ActivationHeight`. Prior to that, the staking dApp form should be disabled with a message "Staking app not active" or something similar.
- If `currentBTCHeight > version0.ActivationHeight` and `currentBTCHeight + 1 + ConfirmationDelta >= nextVersion.ActivationHeight`, i.e. if we are close to a parameters update -> Disable the staking form in a similar way as above.
- `LockTime` should always be set to the activation height of the current parameters.


So some concrete tasks for this:
- Choose the height and parameters properly.
- Enable setting the `LockTime`
- Disable the form using the above conditions.

**Comment by jrwbabylonchain** [comment]
https://github.com/babylonchain/simple-staking/pull/90
https://github.com/babylonchain/simple-staking/pull/80
https://github.com/babylonchain/btc-staking-ts/pull/23
