### ISSUE TITLE
Finality providers random sorting

### ISSUE THREAD

**Issue by gbarkhatov** [babylonchain/simple-staking#72]
Finality providers should be sorted randomly

**Comment by gbarkhatov** [comment]
@jrwbabylonchain do we go with the back-end approach?

**Comment by jrwbabylonchain** [comment]
yes. this had to be done on the backend to avoid bugs. https://github.com/babylonchain/staking-api-service/issues/117

You can close this FE tasks
The priority of the BE for this one shall be low IMO

**Comment by gbarkhatov** [comment]
Closing
