### ISSUE TITLE
Pending X / 6 confirmations

### ISSUE THREAD

**Issue by gbarkhatov** [babylonchain/simple-staking#75]
_Originally posted by @vitsalis in https://github.com/babylonchain/simple-staking/pull/74#discussion_r1601936949_

**Comment by gbarkhatov** [comment]
@vitsalis Compared with `btc-staking-dashboard` we don't use btc tip height as a global mempool API call, we can refetch every 60 seconds or so. It's a part of our btcwallet, that should be called manually.
Do we need this status confirmations at all? If so:
1. We would have to change our wallet interface by adding `getTransactionStatus` `(`${mempoolAPI}tx/${txID}/status`);` or adding this as an external (not wallet related) API call that we constantly refresh each minute or so
2. Then we would have to manually add an effect to each delegation (row in the "table") that goes and fetches both the above and the current tip using the `btcWallet.getTip()`

- If that's a must-have we it will apply the stuff above which I am not happy about
- If that's nice to have we might just change the current tooltip from https://i.imgur.com/tXyeqBU.png to something like "It usually takes 6 confirmations" or "You must wait around an hour"
- Or since we keep the transaction ID, we might just add a link into a tooltip. Though there is a transaction ID right left to this status) so the user can open up the mempool and look at how many confirmations he has.

I am not happy with any of these approaches, should we pick the easier solution?

**Comment by vitsalis** [comment]
Hm I see the problem. Let's do the easier solution for now (I like the second bullet point) and then investigate how could we show the confirmations. Let's keep this issue open though and assign it medium priority.

**Comment by gbarkhatov** [comment]
Okay

**Comment by gbarkhatov** [comment]
Closed in #197
