### ISSUE TITLE
Footer icon lists overflow

### ISSUE THREAD

**Issue by jeremy-babylonchain** [babylonchain/simple-staking#83]
![CleanShot 2024-05-17 at 12 32 12@2x](https://github.com/babylonchain/simple-staking/assets/168515712/a69a71d5-cbf0-4be1-abdc-09fef2ddc672)

Footer gets out of bound when width is smaller than `432px`, would suggest to handle the overflow or adjust the width dynamically.

**Comment by renu-123-pixel** [comment]
hey @jeremy-babylonchain  !can u assign assign this issue to me?
