### ISSUE TITLE
Term / duration field

### ISSUE THREAD

**Issue by gbarkhatov** [babylonchain/simple-staking#87]
- When we have a "regular" form state with min and max term values -> We have to input the staking term to be able to stake and click the button. We have API data as the HTML input constraint and we use internal **react input state value**.
- When we have a "fixed term" (min === max) we don't input the data into the field, because it's hidden. But the form should be able to be submitted and staking transaction to be created, even though we **are relying on API data**

We need to be sure that the code for this part is non-problematic, simple to understand and manage, and that no errors are happening "in-between". This might involve:
- staking form component restructure
- staking logic (`handleSign`) to be checked
- applying all the constraints properly

Keep in mind, that our form is shown when the wallet is not connected

I suggest completing this ticket after the general form validation #76

**Comment by vitsalis** [comment]
Yep, my recommendation is that the source of truth about the staking term is always the react state. If the parameters are the same and we have a fixed term, let's set the state value to the term value when the component loads. Then, if the form for updating the term never appears, the state will never be updated.

**Comment by gbarkhatov** [comment]
Problem here is that generally its an antipattern, to set a react state based on something outside (prop like api data) since it can be derived without setting a state. 
But out component uses multiple forms, so maybe an elegant solution would be to split this component into a multiple sub components. So "full" component keeps both term and amount as state, "fixed term" component only has `amount` as a state, etc.

**Comment by vitsalis** [comment]
Don't exactly understand why this is an anti-pattern. Why is it bad to have this inside a component

```
TermComponent(minTerm, maxTerm, termValueSetCallback) {
    [term, setTerm] = useState(minTerm) // Sets `minTerm` as the default
    termValueSetCallback(minTerm) // Let the upper component know that the default has been set
    if (minTerm == maxTerm) {
        console.log("Terms are the same etc.")
    } else {
        <TermInput onChange=termValueSetCallback />
    }
}
```

Basically, in the static case, `termValueSetCallback` is only set once, while in the other case it is called every time the user modifies the form.
